###GET all blogs
GET http://localhost:3000/blogs

###GET blog by id
GET http://localhost:3000/blogs/2

###POST create blog
POST http://localhost:3000/blogs
Content-Type: application/json  

{
    "title": "My First Blog",
    "description": "This is the description of my first blog.",
    "image": "http://example.com/blog-image.jpg",
    "authorId": 1
}

###PATCH update blog
PATCH http://localhost:3000/blogs/2
Content-Type: application/json

{
    "comments": [
        {
            "content": "Great blog post!"
        },
        {
            "content": "Thanks for sharing."
        }
    ]
}